--- 
document: 
  description: "Queste linee guida sono redatte ai sensi del d.lgs. 150/2009 e dell'articolo 3, comma 1, del dPR n. 105 del 2016 che attribuiscono al Dipartimento della Funzione Pubblica (DFP) le funzioni di indirizzo, coordinamento e monitoraggio in materia di ciclo della performance, avvalendosi del supporto tecnico e metodologico della Commissione Tecnica per la Performance (CTP) di cui all'articolo 4 del citato dPR."
  name: "Linee guida per il sistema di misurazione e valutazione della performance"
  tags: 
    - "linee guida"
